apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remediation-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-agent
subjects:
  - kind: ServiceAccount
    name: remediation-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: remediation-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-agent
  namespace: default
  labels:
    app: remediation-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-agent
  template:
    metadata:
      labels:
        app: remediation-agent
    spec:
      serviceAccountName: remediation-agent
      containers:
        - name: agent
          image: remediation-agent:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_URL
              value: "http://host.docker.internal:11434/api/generate"
            - name: GITHUB_REPO
              value: "hritikmunde/llm-platform"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-agent
  namespace: default
spec:
  selector:
    app: remediation-agent
  ports:
    - port: 80
      targetPort: 8080