apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-agent
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::442042529210:role/remediation-agent-bedrock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remediation-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-agent
subjects:
  - kind: ServiceAccount
    name: remediation-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: remediation-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-agent
  namespace: default
  labels:
    app: remediation-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-agent
  template:
    metadata:
      labels:
        app: remediation-agent
    spec:
      serviceAccountName: remediation-agent
      containers:
        - name: agent
          image: 442042529210.dkr.ecr.us-east-1.amazonaws.com/remediation-agent:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: BEDROCK_MODEL_ID
              value: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
            - name: GITHUB_REPO
              value: "hritikmunde/llm-platform"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-agent
  namespace: default
spec:
  selector:
    app: remediation-agent
  ports:
    - port: 80
      targetPort: 8080