apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: default
  labels:
    app: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        workload: gpu
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.6.3
          args:
            - "--model"
            - "Qwen/Qwen2.5-0.5B-Instruct"
            - "--max-model-len"
            - "8192"
            - "--gpu-memory-utilization"
            - "0.99"
            - "--dtype"
            - "half"
            - "--enable-auto-tool-choice"
            - "--tool-call-parser"
            - "hermes"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: HF_HOME
              value: /tmp/hf
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-svc
  namespace: default
  labels:
    app: vllm
spec:
  selector:
    app: vllm
  ports:
    - name: http
      port: 80
      targetPort: 8000

